spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?useU&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
  resources:
    static-locations: classpath:/static/

mybatis:
  type-aliases-package: com.kele.myblog2.entity
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true




